### ISSUE TITLE
Decide how we want to provide access to the adh executables?

### ISSUE THREAD

**Issue by mfarthin** [jonghyunharrylee/pyPCGA#4]
The pre-compiled adh executables in the adh_red_inset application won't run on our blade server. We may want to point users to AdH website for the binary versions they distribute.

I suppose if we distribute in a docker container we would be ok (either just adh as a docker executable or the whole PCGA application).

**Comment by jonghyunharrylee** [comment]
I am thinking of distributing a docker or singularity container for a general adh application like Savannah but can be the Red River case. Just wonder, am I allowed to distribute a container with stwave and stwave_utils? It seems that this requires ERDC-CHL's approval or one has to purchase commercial one?

**Comment by mfarthin** [comment]
Distributing the stwave executable should be fine. For stwave utils, I think it would be fine if we just include the code necessary for PCGA. There are other routines in there that aren’t ready for prime time that we might need to have approval for if we released them.

**Comment by thesser1** [comment]
Well, I believe Spicer Bak has moved the test bed codes to a public
github (which are a lot of the codes behind the scenes in stwave_utils).
We just need to update our setup to use the newly released codes and I
think we are good shape.

**Comment by jonghyunharrylee** [comment]
Thanks for the reply. I try to prepare stwave-pyPCGA/adh-pyPCGA docker containers soon (hopefully before the paper submissions)
